version: 2.1 # to enable orb usage, you must be using circleci 2.1
# Declare the orbs you wish to use.
# Android orb docs are available here:  https://circleci.com/developer/orbs/orb/circleci/android
orbs:
  codecov: codecov/codecov@3.0.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - codecov/upload:
          token: e5e9a1ac-93df-4a16-bd87-609381106e95 
          url: https://codecov.io/bash 
          when: always 

          
   #   - run:
   #       name: Run Tests
   #       command:sudo chmod +x ./gradlew lint test
   #   - store_artifacts:
   #       path: app/build/reports
   #       destination: reports
   #   - store_test_results:
   #       path: app/build/test-results
